package store
import("database/sql";"fmt";"os";"path/filepath";"time";_ "modernc.org/sqlite")
type DB struct{*sql.DB}
type Bottle struct{ID int64 `json:"id"`;Name string `json:"name"`;Producer string `json:"producer"`;Type string `json:"type"`;Vintage int `json:"vintage"`;Region string `json:"region"`;Quantity int `json:"quantity"`;PriceCents int64 `json:"price_cents"`;EstimatedValueCents int64 `json:"estimated_value_cents"`;TastingNotes string `json:"tasting_notes"`;DrinkFrom int `json:"drink_from"`;DrinkBy int `json:"drink_by"`;CreatedAt time.Time `json:"created_at"`}
func Open(d string)(*DB,error){os.MkdirAll(d,0755);dsn:=filepath.Join(d,"cellar.db")+"?_journal_mode=WAL&_busy_timeout=5000";db,err:=sql.Open("sqlite",dsn);if err!=nil{return nil,fmt.Errorf("open: %w",err)};db.SetMaxOpenConns(1);migrate(db);return &DB{db},nil}
func migrate(db *sql.DB){db.Exec(`CREATE TABLE IF NOT EXISTS bottles(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,producer TEXT DEFAULT '',type TEXT DEFAULT 'red',vintage INTEGER DEFAULT 0,region TEXT DEFAULT '',quantity INTEGER DEFAULT 1,price_cents INTEGER DEFAULT 0,estimated_value_cents INTEGER DEFAULT 0,tasting_notes TEXT DEFAULT '',drink_from INTEGER DEFAULT 0,drink_by INTEGER DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`)}
func(db *DB)Create(b *Bottle)error{res,err:=db.Exec(`INSERT INTO bottles(name,producer,type,vintage,region,quantity,price_cents,estimated_value_cents,tasting_notes,drink_from,drink_by)VALUES(?,?,?,?,?,?,?,?,?,?,?)`,b.Name,b.Producer,b.Type,b.Vintage,b.Region,b.Quantity,b.PriceCents,b.EstimatedValueCents,b.TastingNotes,b.DrinkFrom,b.DrinkBy);if err!=nil{return err};b.ID,_=res.LastInsertId();return nil}
func(db *DB)List(q,typ string)([]Bottle,error){base:=`SELECT id,name,producer,type,vintage,region,quantity,price_cents,estimated_value_cents,tasting_notes,drink_from,drink_by,created_at FROM bottles WHERE quantity>0`;args:=[]interface{}{};if q!=""{base+=` AND (name LIKE ? OR producer LIKE ? OR region LIKE ?)`;args=append(args,"%"+q+"%","%"+q+"%","%"+q+"%")};if typ!=""{base+=` AND type=?`;args=append(args,typ)};base+=` ORDER BY vintage DESC,name`;rows,err:=db.Query(base,args...);if err!=nil{return nil,err};defer rows.Close();var out[]Bottle;for rows.Next(){var b Bottle;rows.Scan(&b.ID,&b.Name,&b.Producer,&b.Type,&b.Vintage,&b.Region,&b.Quantity,&b.PriceCents,&b.EstimatedValueCents,&b.TastingNotes,&b.DrinkFrom,&b.DrinkBy,&b.CreatedAt);out=append(out,b)};return out,nil}
func(db *DB)Drink(id int64){db.Exec(`UPDATE bottles SET quantity=MAX(0,quantity-1) WHERE id=?`,id)}
func(db *DB)Delete(id int64){db.Exec(`DELETE FROM bottles WHERE id=?`,id)}
func(db *DB)Stats()(map[string]interface{},error){var bottles,total int;var value int64;db.QueryRow(`SELECT COUNT(*),COALESCE(SUM(quantity),0) FROM bottles`).Scan(&bottles,&total);db.QueryRow(`SELECT COALESCE(SUM(estimated_value_cents*quantity),0) FROM bottles`).Scan(&value);return map[string]interface{}{"unique_bottles":bottles,"total_bottles":total,"estimated_value_cents":value},nil}
